"""Application and GitHub release metadata."""

APP_NAME = "RTS Converter"
APP_VERSION = "1.1.0"
GITHUB_OWNER = "ilohlove"
GITHUB_REPOSITORY = "rts-converter"
EXECUTABLE_NAME = "RTS Converter.exe"
CHECKSUM_ASSET_NAME = f"{EXECUTABLE_NAME}.sha256"
LEGACY_EXECUTABLE_NAME = "RTZ-to-CSV.exe"
LEGACY_CHECKSUM_ASSET_NAME = f"{LEGACY_EXECUTABLE_NAME}.sha256"
RELEASE_EXECUTABLE_NAMES = (EXECUTABLE_NAME, LEGACY_EXECUTABLE_NAME)
UPDATE_CACHE_DIRECTORY_NAME = APP_NAME
GITHUB_API_VERSION = "2026-03-10"
RELEASES_URL = (
    f"https://github.com/{GITHUB_OWNER}/{GITHUB_REPOSITORY}/releases"
)
LATEST_RELEASE_API = (
    f"https://api.github.com/repos/{GITHUB_OWNER}/{GITHUB_REPOSITORY}/releases/latest"
)

__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "CHECKSUM_ASSET_NAME",
    "EXECUTABLE_NAME",
    "GITHUB_API_VERSION",
    "GITHUB_OWNER",
    "GITHUB_REPOSITORY",
    "LEGACY_CHECKSUM_ASSET_NAME",
    "LEGACY_EXECUTABLE_NAME",
    "LATEST_RELEASE_API",
    "RELEASE_EXECUTABLE_NAMES",
    "RELEASES_URL",
    "UPDATE_CACHE_DIRECTORY_NAME",
]
